

function makeFigure1
global paperFig classLevel1 classLevel2 class1Color class2Color Sp greenColorAdjust



% updated size & units for journal specs on 03/28/2017

% -----------------------------------------------------------------
% RELEVANT MAT FILES WERE GENERATED BY:                      
% calculateSumFigParts.m             (for examples and class odors)
% calculate4thOrderPopResp_v1.m      (for scaling plots, N4=1)
% calculate4thOrderPopResp_popV2.m   (for population plots, N4=200)
% _flyModel/calculate4thOrderPopResp_Fly_antiHebbSmall.m

% -----------------------------------------------------------------
% simplified back to single example of "2-mouse" fig on 6/14/16
% reshaped on 5/20/16
% split into plotting part and data generating part (calculateSumFigParts.m) on 1/5/16
% updated to use only "correlated" odors instead of mix & class on 12/29/15
% -----------------------------------------------------------------

addpath(genpath([pwd,'/_piriformModel']))

paperFig = figure; 
set(gcf,'color','w')
set(gcf,'Units','Centimeters')
%pos=get(gcf,'Position');
%pos(1)=1000;
pos(3)=11.4; %8.5;%pos(3)*1.5;
pos(4)=16.0;%pos(4)*1.5;
set(gcf,'Position',pos)

%aAxes = axes('position',[.11  .69  .35  .2217]); hold on
a0Axes = axes('position',[.11  .94  .35  .025]);
aiAxes = axes('position',[.11  .82  .35  .115]);
aiiAxes = axes('position',[.11  .665  .35  .15]);
annotation('textbox', [.02 .94 .05 .05],...
    'String', 'A','BackgroundColor','none','Color','k',...
    'LineStyle','none','fontsize',16,'HorizontalAlignment','Center');

%subplot(3,6,6+(1:2));
biAxes = axes('position',[.6  .64  .35  .05]); hold on
biiAxes = axes('position',[.55  .69  .05  .35*pos(3)/pos(4)]); hold on
biiiAxes = axes('position',[.6  .69  .35  .35*pos(3)/pos(4)]); hold on
annotation('textbox', [.5 .94 .05 .05],...
    'String', 'B','BackgroundColor','none','Color','k',...
    'LineStyle','none','fontsize',16,'HorizontalAlignment','Center');


cAxes = axes('position',[.11  .3  .35  .35*pos(3)/pos(4)]); hold on
annotation('textbox', [.02 .32+.35*pos(3)/pos(4) .05 .05],...
    'String', 'C','BackgroundColor','none','Color','k',...
    'LineStyle','none','fontsize',16,'HorizontalAlignment','Center');

dAxes = axes('position',[.61  .3  .35  .35*pos(3)/pos(4)]);
annotation('textbox', [.5 .32+.35*pos(3)/pos(4) .05 .05],...
    'String', 'D','BackgroundColor','none','Color','k',...
    'LineStyle','none','fontsize',16,'HorizontalAlignment','Center');

eAxes = axes('position',[.11  .08  .35  .08]);
annotation('textbox', [.02 .2 .05 .05],...
    'String', 'E','BackgroundColor','none','Color','k',...
    'LineStyle','none','fontsize',16,'HorizontalAlignment','Center');

fAxes = axes('position',[.61  .08  .35  .08]); 
annotation('textbox', [.5 .2 .05 .05],...
    'String', 'F','BackgroundColor','none','Color','k',...
    'LineStyle','none','fontsize',16,'HorizontalAlignment','Center');

initializeGlobals;
%load('partsForSumFig_1millionNy.mat');

%% rep heatmap
No = 40;
blueMap = [0*(1:64)',1/(1.5*64)*(64:-1:1)',(1/64)*(64:-1:1)'];
greenMap = [repmat(class2Color,32,1);repmat(class1Color,32,1)];
colormap([greenMap;blueMap;hot(64)])

% first make correlation matrix:
NoTot = 3*No;
Sclass = classLevel2*(ones(2*No)-eye(2*No))+eye(2*No);
Sclass(No+1:end,No+1:end) = classLevel1*(ones(No)-eye(No))+eye(No);
S = eye(NoTot);
S(No+1:end,No+1:end) = Sclass;

[glomRepTemp,odorSimilarity] = makeOdors('correlated',S,NoTot);
glomerulusRepRand = glomRepTemp(:,1:No);
similarityRand = -eps*(odorSimilarity(1:No)<0); 
glomerulusRepCorr2 = glomRepTemp(:,No+1:2*No);
similarityClass2 = -2 + odorSimilarity(No+1:2*No);
glomerulusRepCorr1 = glomRepTemp(:,2*No+1:end);
similarityClass1 = -2 + odorSimilarity(2*No+1:end);

% %random
[piriformRepRand,~,~,J] = makePiriform(glomerulusRepRand);

%graded
piriformRepClass1 = makePiriform(glomerulusRepCorr1,Sp,J);
piriformRepClass2 = makePiriform(glomerulusRepCorr2,Sp,J);

%combined for figure
glomerulusRep = [glomerulusRepRand,glomerulusRepCorr2,glomerulusRepCorr1];%,glomRepTempMix];
piriformRep = [piriformRepRand,piriformRepClass2,piriformRepClass1];%,piriformRepMix];


oPlotIdx = 1:3*No; 

% glomeruli ---------
gPlotIdx = [1:15, 31:50, 101:115];
glomerulusRepScaledForFig = glomerulusRep(gPlotIdx,oPlotIdx)/max(.7*max(glomerulusRep(gPlotIdx,oPlotIdx)));
axes(aiAxes)
imagesc(glomerulusRepScaledForFig);
box off;
ylabel('Bulb','fontsize',12); 
set(gca,'YTick',[])
set(gca,'XTick',[])
caxis([-2 1])
axes(a0Axes)
imagesc([similarityRand,similarityClass2,similarityClass1]);%,mixtureOdorSimilarity])
axis off
caxis([-2 1]); %caxis([-1 1]); %
text( No/2, 1, 'rand','fontweight','bold','horizontalalignment','center','color',[1 1 1]);
text( No+No/2, 1, '30%','fontweight','bold','horizontalalignment','center','color',[1 1 1]);
text( 2*No+No/2, 1, '70%','fontweight','bold','horizontalalignment','center','color',[1 1 1]);

% piriform -----------
axes(aiiAxes)
pPlotIdx = 1:50;
piriformRepScaledForFig = piriformRep(pPlotIdx,oPlotIdx)/max(.7*max(piriformRep(pPlotIdx,oPlotIdx)));
imagesc(piriformRepScaledForFig);
caxis([-2 1])

box off;
xlabel('Odor','fontsize',12)
ylabel('Piriform','fontsize',12); %['Piriform Neuron (',num2str(Ny),' total)']
set(gca,'YTick',[])
set(gca,'XTick',[])
caxis([-2 1])


%% correlation fig
load('_simResults/partsForSumFig.mat');
axes(biAxes) 
hrange = -0.1:max(glomCorr)/100:max(glomCorr); %0:.01:1; %hrange = 0:1:201; 

hout = hist(glomCorr(corrIsRandIdx),hrange)/sum(corrIsRandIdx);
hin1 = hist(glomCorr(corrIsClass1Idx),hrange)/sum(corrIsClass1Idx);
hin2 = hist(glomCorr(corrIsClass2Idx),hrange)/sum(corrIsClass2Idx);
fill([hrange(1),hrange,hrange(end)],[0,-hout,0],'k','linewidth',1); hold on
fill([hrange(1),hrange,hrange(end)],[0,-hin2,0],class2Color,'linewidth',1); hold on
fill([hrange(1),hrange,hrange(end)],[0,-hin1,0],class1Color,'linewidth',1); hold on
xlim([-0.1 1])
ylim([-.2 0])
box off;
axis off
ylabel('P(r)','fontsize',11)


axes(biiAxes)
hrange = -0.05:max(pirCorr)/100:max(pirCorr); %0:.01:1; %hrange = 0:1:201; 

hout = hist(pirCorr(corrIsRandIdx),hrange)/sum(corrIsRandIdx);
hin1 = hist(pirCorr(corrIsClass1Idx),hrange)/sum(corrIsClass1Idx);
hin2 = hist(pirCorr(corrIsClass2Idx),hrange)/sum(corrIsClass2Idx);
fill([0,0,-hout,0,0],[0,hrange(1),hrange,hrange(end),0],'k','linewidth',1); hold on
fill([0,-hin2,0],[hrange(1),hrange,hrange(end)],class2Color,'linewidth',1); hold on
fill([0,-hin1,0],[hrange(1),hrange,hrange(end)],class1Color,'linewidth',1); hold on
ylim([-0.05 1])
xlim([-.2 0])
box off;
axis off
xlabel('P(r)','fontsize',11)


% correlations -------------
axes(biiiAxes)

%corrIsMixtureLoc = find(corrIsMixtureIdx);
corrIsClass1Loc = find(corrIsClass1Idx);
corrIsClass2Loc = find(corrIsClass2Idx);
corrIsOtherLoc = find(corrIsRandIdx);

plot( glomCorr( corrIsMixtureIdx ) ,    pirCorr( corrIsMixtureIdx ),'.', 'color', [.87 .87 .87],'markersize',12); hold on
plot(glomCorr(  corrIsClass1Loc ) ,  pirCorr( corrIsClass1Loc ),'.', 'color', class1Color,'markersize',5)
plot(glomCorr(  corrIsClass2Loc ) ,  pirCorr( corrIsClass2Loc ),'.', 'color', class2Color,'markersize',5)
plot(glomCorr(  corrIsOtherLoc ) ,  pirCorr( corrIsOtherLoc ),'k.','markersize',5)

box off
xlabel('Glomerular Correlation','fontsize',11)
ylabel('Piriform Correlation','fontsize',11)
xlim([-0.1 1]);
ylim([-0.05 1]);
set(gca,'Xtick',0:.25:1)
set(gca,'Ytick',0:.25:1)
set(gca,'XtickLabels',{0,'',.5,'',1})
set(gca,'YtickLabels',{0,'',.5,'',1})

text( .05, .86, 'Nonclass','color',[0 0 0],'FontSize',10);
text( .05, .8, [num2str(classLevel2*100),'% overlap'],'color',class2Color,'FontSize',10);
text( .05, .74, [num2str(classLevel1*100),'% overlap'],'color',class1Color,'FontSize',10);

display(['Rand (glom): ',num2str(mean(glomCorr(  corrIsOtherLoc )))])
display(['Rand (pir): ',num2str(mean(pirCorr(  corrIsOtherLoc )))])
display(['Class1 (glom): ',num2str(mean(glomCorr(  corrIsClass1Loc )))])
display(['Class1 (pir): ',num2str(mean(pirCorr(  corrIsClass1Loc )))])
display(['Class2 (glom): ',num2str(mean(glomCorr(  corrIsClass2Loc )))])
display(['Class2 (pir): ',num2str(mean(pirCorr(  corrIsClass2Loc )))])

%% model overlap
axes(cAxes); hold on
z = load('_simResults/partsForFig1odorPairComparison.mat');
plot(z.pirRepFreqClass2Expected,z.pirRepFreqClass2Observed,'.','markersize',7,'color',class2Color);hold on
plot(z.pirRepFreqClass1Expected,z.pirRepFreqClass1Observed,'.','markersize',7,'color',class1Color);
plot(z.pirRepFreqRandExpected,z.pirRepFreqRandObserved,'.','markersize',7,'color',[0 0 0]); hold on
box off;
xlabel('Chance Frequency','fontsize',10)
ylabel('Observed Frequency','fontsize',10)
xlim([0 .03]);
ylim([0 .03]);
set(gca,'XTick',0:.01:.03,'fontsize',10);
set(gca,'YTick',0:.01:.03,'fontsize',10);
plot(xlim,ylim,'color',[.5 .5 .5],'linewidth',1)
alpha(.7);

%% data overlap 
axes( dAxes )
text(0.1,0.5,'See Excel file for data')

%% selectivity

randClassColor = [.9 .5 0];

load('_simResults/part1ForImportanceFig_pInv.mat');
load('_simResults/part2ForImportanceFig_pInv.mat');

axes(eAxes); hold on
db = .005; b = 0:db:0.8;
hr = hist( sum(randResponsesPt1>0,2)/size(randResponsesPt1,2), b)/(size(randResponsesPt1,1)*db);
hc = hist( sum(classResponsesPt1>0,2)/size(classResponsesPt1,2), b)/(size(randResponsesPt1,1)*db);
area(b, hr, 'FaceColor','k'); hold on
area(b, hc, 'FaceColor', class1Color);
box off
ylim([0 15]);
xlim([0 b(end)]);
set(gca,'YTick',ylim)
set(gca,'XTick',0:.2:.8)
xlabel('Fraction of Odors','fontsize',10)
ylabel('Prob. Density','fontsize',10)

axes(fAxes); hold on
hr = hist( sum(randResponsesPt2>0,2)/size(randResponsesPt2,2), b)/(size(randResponsesPt1,1)*db);
hc = hist( sum(classResponsesPt2>0,2)/size(classResponsesPt2,2), b)/(size(randResponsesPt1,1)*db);
area(b, hr, 'FaceColor','k'); hold on
area(b, hc, 'FaceColor', randClassColor);
box off
ylim([0 15]);
xlim([0 b(end)]);
set(gca,'YTick',ylim)
set(gca,'XTick',0:.2:.8)
xlabel('Fraction of Odors','fontsize',10)
ylabel('Prob. Density','fontsize',10)





